GastonCardenasBlogEngine.test.Web/Areas/PublishFlow/Models/Publish/PostInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Models.Publish
{
    public class PostInputModel
    {
        public int PostId { get; set; }

        [Required(ErrorMessage = "{0} field is required")]
        [StringLength(300, ErrorMessage = "{0} field only allows 300 characters")]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required(ErrorMessage = "{0} field is required")]
        [StringLength(4000, ErrorMessage = "{0} field only allows 4000 characters")]
        [Display(Name = "Post Content")]
        public string Text { get; set; }

        public int PostStatusId { get; set; }
        public string PostStatusName { get; set; }

        public string SendType { get; set; }
        public bool IsEditMode { get; set; }
    }
}

GastonCardenasBlogEngine.test.Web/Areas/PublishFlow/Models/Publish/PostsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GastonCardenas.Test.Domain.Posts;

namespace GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Models.Publish
{
    public class PostsViewModel
    {
        public IEnumerable<Post> Posts { get; set; }
    }
}

GastonCardenasBlogEngine.test.Web/Models/Posts/PostDetailViewModel.cs
using System.ComponentModel.DataAnnotations;
using GastonCardenas.Test.Domain.Posts;

namespace GastonCardenasBlogEngine.test.Web.Models.Posts
{
    public class PostDetailViewModel
    {
        public Post Post { get; set; }

        public int PostId { get; set; }

        [Required(ErrorMessage = "{0} field is required")]
        [StringLength(100, ErrorMessage = "{0} field only allows 100 characters")]
        [Display(Name = "Comment author")]
        public string AuthorName { get; set; }

        [Required(ErrorMessage = "{0} field is required")]
        [StringLength(100, ErrorMessage = "{0} field only allows 100 characters")]
        [Display(Name = "Comment email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "{0} field is an invalid email")]
        public string AuthorEmail { get; set; }

        [Required(ErrorMessage = "{0} field is required")]
        [StringLength(4000, ErrorMessage = "{0} field only allows 4000 characters")]
        [Display(Name = "Comment")]
        public string Comment { get; set; }
    }
}

GastonCardenasBlogEngine.test.Web/Areas/PublishFlow/Controllers/PublishController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GastonCardenas.Test.Domain.Posts;
using GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Models.Publish;
using GastonCardenasBlogEngine.test.Web.App;

namespace GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Controllers
{
    [Area("PublishFlow")]
    [Authorize(Roles = "Editor,Writer")]
    public class PublishController : Controller
    {
        IPostsService _postsService;
        IPostsApprovalFlowService _postsApprovalFlowService;

        public PublishController(IPostsService postsService, IPostsApprovalFlowService postsApprovalFlowService)
        {
            _postsService = postsService;
            _postsApprovalFlowService = postsApprovalFlowService;
        }

        public async Task<IActionResult> Index()
        {
            PostsViewModel model = new PostsViewModel();
            model.Posts = await _postsService.GetAllPosts();
            return View(model);
        }

        public async Task<IActionResult> Post(int? id)
        {
            PostInputModel model = new PostInputModel();

            if (id.HasValue)
            {
                var post = await _postsService.GetPost(id.Value);
                if (post != null)
                {
                    model.Title = post.Title;
                    model.Text = post.Text;
                    model.PostStatusId = post.PostStatusId;
                    model.PostStatusName = post.PostStatus.Name;
                    model.IsEditMode = true;
                }
            }
            else
                model.PostStatusName = "Draft";

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(int? id, PostInputModel model)
        {
            //Evaluate each submit type
            switch (model.SendType)
            {
                case "SAVE":
                    if (ModelState.IsValid)
                    {
                        Post post = null;
                        if (id.HasValue)
                        {
                            post = await _postsService.GetPost(id.Value);
                            post.Update(model.Title, model.Text);
                            await _postsApprovalFlowService.UpdatePost(post);
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            post = new Post(model.Title, model.Text, User.Identity.Name);
                            int postId = await _postsApprovalFlowService.AddPost(post);

                            return RedirectToAction("Post", new { id = postId });
                        }
                    }
                    break;
                case "APPROVE":
                    if (id.HasValue)
                    {
                        var post = await _postsService.GetPost(id.Value);
                        post.UpdatePostStatus(GastonCardenas.Test.Domain.Enum.PostStatusEnum.PendingPublishApproval, User.Identity.Name);
                        await _postsApprovalFlowService.UpdatePost(post);

                        return RedirectToAction("Index");
                    }
                    break;
                case "PUBLISH":
                    if (id.HasValue)
                    {
                        var post = await _postsService.GetPost(id.Value);
                        post.UpdatePostStatus(GastonCardenas.Test.Domain.Enum.PostStatusEnum.Published, User.Identity.Name);
                        await _postsApprovalFlowService.UpdatePost(post);

                        return RedirectToAction("Index");
                    }
                    break;
                case "REJECT":
                    if (id.HasValue)
                    {
                        var post = await _postsService.GetPost(id.Value);
                        post.UpdatePostStatus(GastonCardenas.Test.Domain.Enum.PostStatusEnum.Draft, User.Identity.Name);
                        await _postsApprovalFlowService.UpdatePost(post);

                        return RedirectToAction("Index");
                    }
                    break;
                case "DELETE":
                    if (id.HasValue)
                    {
                        await _postsApprovalFlowService.RemovePost(id.Value);
                        return RedirectToAction("Index");
                    }
                    break;
            }

            if (id.HasValue)
            {
                var post = await _postsService.GetPost(id.Value);
                if (post != null)
                {
                    model.Title = post.Title;
                    model.Text = post.Text;
                    model.PostStatusId = post.PostStatusId;
                    model.PostStatusName = post.PostStatus.Name;
                }
            }
            else
                model.PostStatusName = "Draft";

            return View(model);
        }
    }
}

GastonCardenasBlogEngine.test.Web/Areas/PublishFlow/Views/Publish/Index.cshtml
@model GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Models.Publish.PostsViewModel
@{ ViewData["Title"] = "Posts";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="row">
    <div class="col-sm-12">
        <h1>All Posts</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Approved by</th>
                    <th>Approval date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var post in Model.Posts)
                {
    <tr>
        <th scope="row">@post.PostId</th>
        <td>@post.CreationtDate.ToString("dd-MM-yyyy")</td>
        <td>@post.Title</td>
        <td>@post.AuthorName</td>
        <td>@post.PostStatus.Name</td>
        <td>@post.ApproverName</td>
        <td>
            @if (post.ApprovalDate.HasValue)
            {@(post.ApprovalDate.Value.ToString("dd-MM-yyyy"))}
        </td>
        <td>
            <a class="btn btn-primary" href="@Url.Action("Post", "Publish", new { id = post.PostId, area = "PublishFlow" })" title="Edit"> <span class="glyphicon glyphicon-edit">Edit</span></a>
        </td>
    </tr>}
            </tbody>
        </table>
    </div>
    <div class="col-sm-12">
        @if (User.IsInRole("Writer"))
        {
            <a asp-area="PublishFlow" asp-controller="Publish" asp-action="Post" class="btn btn-primary pull-right"> 
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Post</a>
        }
    </div>
</div>

GastonCardenasBlogEngine.test.Web/Areas/PublishFlow/Views/Publish/Post.cshtml
@model GastonCardenasBlogEngine.test.Web.Areas.PublishFlow.Models.Publish.PostInputModel
@{ ViewData["Title"] = $"Post Detail - {Model.Title}";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="row">
    <div class="col-sm-12">
        <h1>Post Detail (@Model.PostStatusName)</h1>

        <form asp-antiforgery="true">
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                @Html.ValidationMessageFor(t => t.Title)
            </div>
            <div class="form-group">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" rows="10" class="form-control"></textarea>
                @Html.ValidationMessageFor(t => t.Text)
            </div>
            @if (Model.PostStatusId == (int)GastonCardenas.Test.Domain.Enum.PostStatusEnum.Draft && User.IsInRole("Writer"))
            {
<button type="submit" name="SendType" value="SAVE" class="btn btn-success">Save</button>            }
            @if (Model.IsEditMode)
            {
@if (Model.PostStatusId == (int)GastonCardenas.Test.Domain.Enum.PostStatusEnum.Draft && User.IsInRole("Writer"))
{
<button type="submit" name="SendType" value="APPROVE" class="btn btn-primary">Send for approval</button>                }
                @if (Model.PostStatusId == (int)GastonCardenas.Test.Domain.Enum.PostStatusEnum.PendingPublishApproval && User.IsInRole("Editor"))
                {
<button type="submit" name="SendType" value="REJECT" class="btn btn-warning">Reject</button>
                    <button type="submit" name="SendType" value="PUBLISH" class="btn btn-success">Publish</button>                }
                                @if ((Model.PostStatusId == (int)GastonCardenas.Test.Domain.Enum.PostStatusEnum.Published || Model.PostStatusId == (int)GastonCardenas.Test.Domain.Enum.PostStatusEnum.Draft) && User.IsInRole("Writer"))
                                {
                <button type="submit" name="SendType" value="DELETE" class="btn btn-danger">Delete</button>                }            }
            <input type="hidden" asp-for="IsEditMode" />
        </form>
    </div>
    <div class="col-sm-12">
        <a asp-area="PublishFlow" asp-controller="Publish" asp-action="Index" class="btn btn-default pull-right"> <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back to posts</a>
    </div>
</div>