GastonCardenasBlogEngine.test.Web/Controllers/SecurityController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using GastonCardenasBlogEngine.test.Web.Models.Login;

namespace GastonCardenasBlogEngine.test.Web.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            if (ModelState.IsValid)
            {
                switch (model.Username.ToLower())
                {
                    case "viewer":
                        await AuthenticateUser(model.Username, "User");
                        return RedirectToAction("Index", "Home");
                    case "editor":
                        await AuthenticateUser(model.Username, "Editor");
                        return RedirectToAction("Index", "Publish", new { Area = "PublishFlow" });
                    case "writer":
                        await AuthenticateUser(model.Username, "Writer");
                        return RedirectToAction("Index", "Publish", new { Area = "PublishFlow" });
                    default:
                        ModelState.AddModelError("Login", "Invalid user or password");
                        break;
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return Redirect("/");
        }

        private async Task AuthenticateUser(string user, string role)
        {
            var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, user)
                        };

            claims.Add(new Claim(ClaimTypes.Role, role));

            var claimsIdentity = new ClaimsIdentity(
                            claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                RedirectUri = "/"
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);
        }
    }
}

GastonCardenasBlogEngine.test.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog Engine</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GastonCardenasBlogEngine.test.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="Login"> <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Users Login</a>
            </li> }
                        else
                        {
                            if (User.IsInRole("Writer") || User.IsInRole("Editor"))
                            {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="PublishFlow" asp-controller="Publish" asp-action="Index"> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Manage Posts</a>
            </li> }

            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="Logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Logout</a>
            </li>}
                    </ul>
                </div>
                <div class="pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
        <a href="javascript:;"><br />@User.Identity.Name.ToUpper()</a>}
                </div>
            </div>
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GastonCardenasBlogEngine.test.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <partial name="_ValidationScriptsPartial" />

    @RenderSection("Scripts", required: false)
</body>
</html>